---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .BootstraptConfigMapName }}
  namespace: {{ .Namespace }}
data:
  bootstrapt.sh: "{{ .BootstraptContent }}"
